language: node_js
node_js:
- iojs
- '7'
env:
  global:
    secure: slUwKX3w+s4ZKotGAD/WixAw793ljQLyZipZWHw6cZKhavfrqKJ6vC6HzBeHaRo4UEzTCZ9jX59lZQShTA7b7Z+qO2Rr1skhYCWpUJhyr2ixa9oJnUjhre1jhpqqLSp8z2OvCvesvZ+jsQZydkDiLi4IcsDqH/+idruoZV3oaJkDuWmNBKQuyHdAAcFY8Lil28onm8pudTY0JtBj26xnko5r0G3a2mnlUMESYEtdxcbVVZCkLRt6GWWnKNiIsrEQPkW8QutH8tL6BfpKw7nB99K8yLBpZjommP36rMx5v09IBHZn+TcEJD+4Nkl/dvqaY5NaTgeXjarZC9w69OkHSwGr1tTUTqfR6To8CuPXGx9bajAIW2o/HclksSrCSxv9GRC3XUbkz7ej829aTDWAc1bG8ve2XjXn77Y73GZS17rjG5dVMMfjse0sPZCaVx2LopY/8BbBD0wdsFJWr04wb2x9sYyxBspOwMVypOtvez6FBC+Yi6QUuxJlLlCYW9z8dg2dVVpc1r1tcGdm3wyfnMwGmJbaiqSoPf385LUCucbKSgN6kBMwel8OFt2ub3c7jWvvZGExggr4P4R7UDnMl9aXbjqxUizsStP9iozctpoDq4PB+d5lYIoJeTWqaXdZMjba0MbpMMjBEVsSTUEvoSGotEMPINPBwdlqeSWU3AE=
